stages:
  - build_and_push
  - deploy

build_and_push:
  stage: build_and_push
  image: docker:stable
  services:
    - name: docker:dind
      alias: dockerhost
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  script:
    - apk update -qy && apk add --no-cache curl unzip bash
    - apk add --no-cache python3 && python3 -m ensurepip && rm -r /usr/lib/python*/ensurepip && pip3 install --upgrade pip setuptools && if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && if [[ ! -e /usr/bin/python ]]; then ln -sf /usr/bin/python3 /usr/bin/python; fi && rm -r /root/.cache
    - pip3 install awscli
    - $(aws ecr get-login --no-include-email --region $AWS_REGION)
    - docker build -t $ECR_REPO_BACKEND .
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_FRONTEND_URL
    - docker tag $ECR_REPO_BACKEND:latest $ECR_FRONTEND_URL/$ECR_REPO_BACKEND:latest
    - docker push $ECR_FRONTEND_URL/$ECR_REPO_BACKEND:latest
  only:
    - backend

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_BACKEND_SERVICE --force-new-deployment --region $AWS_REGION --task-definition $ECS_BACKEND_TASK_DEF --no-cli-pager
  only:
    - backend